version: '3.7'
services:
    directus-db:
        image: 'mariadb:10.6.3'
        container_name: directus-db
        networks:
            - directus
        environment:
            MYSQL_DATABASE: main
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: directus
        volumes:
            - ./api/data:/var/lib/mysql

    directus-cache:
        container_name: directus-cache
        image: redis:6
        networks:
            - directus

    directus-app:
        container_name: directus-app
        image: directus/directus:9
        ports:
            - 8055:8055
        volumes:
            - ./api/uploads:/directus/uploads
            - ./api/extensions:/directus/extensions
        networks:
            - directus
        depends_on:
            - directus-cache
            - directus-db
        environment:
            KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
            SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

            DB_CLIENT: 'mysql'
            DB_HOST: 'directus-db'
            DB_PORT: '3306'
            DB_DATABASE: 'main'
            DB_USER: 'root'
            DB_PASSWORD: 'password'

            CACHE_ENABLED: 'true'
            CACHE_STORE: 'directus-cache'
            CACHE_REDIS: 'redis://cache:6379'

            # ADMIN_EMAIL: 'admin@exemple.com'
            # ADMIN_PASSWORD: 'password '
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        environment:
            ADMINER_DESIGN: dracula
            ADMINER_DEFAULT_SERVER: directus-db
        depends_on:
            - directus-db
        ports:
            - '9000:8080'
        networks:
            - directus

networks:
    directus:
